baseURL: "https://ssungwxx.github.io/"
title: SugnwooKim
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: UA-123-45

minify:
  disableXML: true

DefaultContentLanguage: ko

languages:
  ko:
    languageName: "Korean"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10

params:
  env: production
  title: https://ssungwxx.github.io
  author: Sungwoo Kim

  images: ["papermod-cover.png"]

  ShowShareButtons: true
  comments: true
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecail1stPost: false

  assets:
    disableFingerprinting: true

  label:
    text: "Software engineer blog"

  homeInfoParams:
    Title: ê¹€ì„±ìš° | SungwooKim
    Content: |
      ì•ˆë…•í•˜ì„¸ìš” ìƒˆë¡œìš´ ë„ì „ì„ ì¢‹ì•„í•˜ëŠ” ê°œë°œì ê¹€ì„±ìš°ì…ë‹ˆë‹¤. \
      í•„ìš”í•˜ë‹¤ê³  ëŠë¼ê¸°ì „ì— ë¯¸ë¦¬ ìƒˆë¡œìš´ ê²ƒì„ ì•Œì•„ë³´ê³  ì„ í–‰í•˜ëŠ” ì‘ì—…ì„ ì¢‹ì•„í•©ë‹ˆë‹¤. ìµœê·¼ ê´€ì‹¬ì„ ê°€ì§€ê³  ìˆëŠ” ë„ë©”ì¸ì€  ***Spring***ê³¼ ***Kubernetes*** ì…ë‹ˆë‹¤. \
      ***ìë™í™”***ì™€ ***ê°„ê²°í•¨***ì„ ì¢‹ì•„í•˜ì—¬ ë³µì¡í•˜ê³  ë°˜ë³µë˜ëŠ” ê²ƒì„ ì¤„ì¼ë ¤ê³  ë…¸ë ¥í•©ë‹ˆë‹¤. ìƒˆë¡œìš´ ì½”ë“œë¥¼ ì§œì„œ ì¶”ê°€í•˜ëŠ” ê²ƒë³´ë‹¤ ê¸°ì¡´ì˜ ì½”ë“œë¥¼ ê°œì„ í•˜ì—¬ ê°„ê²°í•˜ê³  íš¨ìœ¨ì ìœ¼ë¡œ ì‘ì—…í•˜ê³ ì ë…¸ë ¥í•©ë‹ˆë‹¤. \
      ê°œë°œë¿ë§Œ ì•„ë‹ˆë¼ ê²Œì„, ì¹µí…Œì¼ ì œì¡°, ë¨¹ê±°ë¦¬ íƒë°©, ê³ ì–‘ì´ë„ ì¢‹ì•„í•©ë‹ˆë‹¤. ëˆ„êµ¬ë“  ë§Œë‚˜ê²Œ ëœë‹¤ë©´ ë‹¤ì–‘í•œ ì´ì•¼ê¸°ë¥¼ ë‚˜ëˆ„ê³  ì‹¶ì–´ìš”. ğŸ™‹ğŸ»
  socialIcons:
    - name: github
      url: "https://github.com/ssungwxx"
    - name: email
      url: "sungwoo.dev@gmail.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/sungwoo-kim-3ab2101a4/"
